from enum import Enum


class PermissionEnum(Enum):
# ENUM FOR 'AUTHENTIACTION' APP	

	# USER PERMISSIONS
	USER_CREATE = 'USER_CREATE'
	USER_UPDATE = 'USER_UPDATE'
	USER_DELETE = 'USER_DELETE'
	USER_LIST = 'USER_LIST'
	USER_DETAILS = 'USER_DETAILS'

	# EMPLOYEE PERMISSIONS
	EMPLOYEE_CREATE = 'EMPLOYEE_CREATE'
	EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE'
	EMPLOYEE_DELETE = 'EMPLOYEE_DELETE'
	EMPLOYEE_LIST = 'EMPLOYEE_LIST'
	EMPLOYEE_DETAILS = 'EMPLOYEE_DETAILS'

	# PERMISSION PERMISSIONS
	PERMISSION_CREATE = 'PERMISSION_CREATE'
	PERMISSION_UPDATE = 'PERMISSION_UPDATE'
	PERMISSION_DELETE = 'PERMISSION_DELETE'
	PERMISSION_LIST = 'PERMISSION_LIST'
	PERMISSION_DETAILS = 'PERMISSION_DETAILS'

	# ROLE PERMISSION
	ROLE_CREATE = 'ROLE_CREATE'
	ROLE_UPDATE = 'ROLE_UPDATE'
	ROLE_DELETE = 'ROLE_DELETE'
	ROLE_LIST = 'ROLE_LIST'
	ROLE_DETAILS = 'ROLE_DETAILS'


# ENUM FOR 'DEIVICE' APP	

	# USER PERMISSIONS
	CATEGORY_CREATE = 'CATEGORY_CREATE'
	CATEGORY_UPDATE = 'CATEGORY_UPDATE'
	CATEGORY_DELETE = 'CATEGORY_DELETE'
	CATEGORY_LIST = 'CATEGORY_LIST'
	CATEGORY_DETAILS = 'CATEGORY_DETAILS'

	# DEVICE PERMISSIONS
	DEVICE_CREATE = 'DEVICE_CREATE'
	DEVICE_UPDATE = 'DEVICE_UPDATE'
	DEVICE_DELETE = 'DEVICE_DELETE'
	DEVICE_LIST = 'DEVICE_LIST'
	DEVICE_DETAILS = 'DEVICE_DETAILS'

	# DEVICE_ASSIGN PERMISSIONS
	DEVICE_ASSIGN_CREATE = 'DEVICE_ASSIGN_CREATE'
	DEVICE_ASSIGN_UPDATE = 'DEVICE_ASSIGN_UPDATE'
	DEVICE_ASSIGN_DELETE = 'DEVICE_ASSIGN_DELETE'
	DEVICE_ASSIGN_LIST = 'DEVICE_ASSIGN_LIST'
	DEVICE_ASSIGN_DETAILS = 'DEVICE_ASSIGN_DETAILS'

	# DEVICE_RETURN PERMISSIONS
	DEVICE_RETURN_CREATE = 'DEVICE_RETURN_CREATE'
	DEVICE_RETURN_UPDATE = 'DEVICE_RETURN_UPDATE'
	DEVICE_RETURN_DELETE = 'DEVICE_RETURN_DELETE'
	DEVICE_RETURN_LIST = 'DEVICE_RETURN_LIST'
	DEVICE_RETURN_DETAILS = 'DEVICE_RETURN_DETAILS'

	# DEVICE_LOG PERMISSIONS
	DEVICE_LOG_CREATE = 'DEVICE_LOG_CREATE'
	DEVICE_LOG_UPDATE = 'DEVICE_LOG_UPDATE'
	DEVICE_LOG_DELETE = 'DEVICE_LOG_DELETE'
	DEVICE_LOG_LIST = 'DEVICE_LOG_LIST'
	DEVICE_LOG_DETAILS = 'DEVICE_LOG_DETAILS'



