from enum import Enum


class PermissionEnum(Enum):

# ENUM FOR 'AUTHENTIACTION' APP	

	# USER PERMISSIONS
	USER_CREATE = 'USER_CREATE'
	USER_UPDATE = 'USER_UPDATE'
	USER_PARTIAL_UPDATE = 'USER_PARTIAL_UPDATE'
	USER_DELETE = 'USER_DELETE'
	USER_LIST = 'USER_LIST'
	USER_DETAILS = 'USER_DETAILS'

	# PERMISSION PERMISSIONS
	PERMISSION_CREATE = 'PERMISSION_CREATE'
	PERMISSION_UPDATE = 'PERMISSION_UPDATE'
	PERMISSION_PARTIAL_UPDATE = 'PERMISSION_PARTIAL_UPDATE'
	PERMISSION_DELETE = 'PERMISSION_DELETE'
	PERMISSION_LIST = 'PERMISSION_LIST'
	PERMISSION_DETAILS = 'PERMISSION_DETAILS'

	# ROLE PERMISSION
	ROLE_CREATE = 'ROLE_CREATE'
	ROLE_UPDATE = 'ROLE_UPDATE'
	ROLE_DELETE = 'ROLE_DELETE'
	ROLE_LIST = 'ROLE_LIST'
	ROLE_DETAILS = 'ROLE_DETAILS'

	# CATEGORY PERMISSION
	CATEGORY_CREATE = 'CATEGORY_CREATE'
	CATEGORY_UPDATE = 'CATEGORY_UPDATE'
	CATEGORY_DELETE = 'CATEGORY_DELETE'
	CATEGORY_LIST = 'CATEGORY_LIST'
	CATEGORY_DETAILS = 'CATEGORY_DETAILS'



