# Generated by Django 3.2.16 on 2023-01-27 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_user_username'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceassign',
            options={'ordering': ('-id',), 'verbose_name_plural': 'DeviceAssign'},
        ),
        migrations.AlterModelOptions(
            name='devicereturn',
            options={'ordering': ('-id',), 'verbose_name_plural': 'DeviceReturn'},
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_categories', to='authentication.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deviceassign',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_assigns', to='device.device'),
        ),
        migrations.AlterField(
            model_name='deviceassign',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assign_devices', to='authentication.employee'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_logs', to='device.device'),
        ),
        migrations.AlterField(
            model_name='devicereturn',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_returns', to='device.device'),
        ),
        migrations.AlterField(
            model_name='devicereturn',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_return_devices', to='authentication.employee'),
        ),
    ]
